"""Domain schemas for content structure (Document, Segment)"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/domains/structure.ipynb.

# %% auto 0
__all__ = ['Document', 'Segment']

# %% ../../nbs/domains/structure.ipynb 3
from typing import Optional
from pydantic import Field

from ..core import DomainNode

# %% ../../nbs/domains/structure.ipynb 5
class Document(DomainNode):
    """A logical container for structured content."""
    
    title: str = Field(..., description="Title of the document")  # Document title
    media_type: str = Field("audio", description="Source media type")  # 'audio', 'video', or 'text'

# %% ../../nbs/domains/structure.ipynb 10
class Segment(DomainNode):
    """An atomic unit of text within a document."""
    
    text: str = Field(..., description="The segment text content")  # Segment text
    index: int = Field(..., description="Sequence position (0-indexed)")  # Position in sequence
    start_time: Optional[float] = Field(None, description="Start time in seconds")  # Audio/video start
    end_time: Optional[float] = Field(None, description="End time in seconds")  # Audio/video end
    role: str = Field("content", description="Segment role")  # 'content', 'title', or 'heading'
